[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://51.24.115.171/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "http://51.24.115.171/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
